### ISSUE TITLE
How do I install this with composer

### ISSUE THREAD

**Issue by sainttech** [gionnivaleriana/laravel-webconsole#1]
How do I install this with copmposer???

Im VERY new to laravel

**Comment by gionnivaleriana** [comment]
Dude, I'm not maintaining this repo anymore..so use it at your own risk (means: no updates, no bug fixing, no security patches..)

However, since this repo is not packed and not present on Packagist.org, you should consider it as a private repo: https://getcomposer.org/doc/articles/handling-private-packages-with-satis.md

Form the Composer guide to private repos:
In your standard `composer.json` file you should have an empty array named `repositories`.
So add in that array the url of the private repo like this:
```json
{
  "name": "My Laravel Project",
  "homepage": "http://packages.example.org",
  "repositories": [
    {
      "type": "vcs",
      "url": "https://github.com/gionnivaleriana/laravel-webconsole"
    }
  ],
  "require-all": true
}
```

After that you can install this repo with composer:
In your console digit (using `dev-master` as version, since it has no official version but is still in development):
```bash
php composer require gionnivaleriana/laravel-webconsole dev-master
```

Please remember to also install the main dependency: `nickola/web-console` at version 0.9.5
